[project]
name = "03-personal-finance-tacker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "questionary>=2.1.1",
    "rich>=14.2.0",
    "streamlit>=1.52.2",
]
